version: '3.8'

services:
  authentication:
    build: ./backend/authentication
    ports:
      - "3001:3000"
  
  courses:
    build: ./backend/courses
    ports:
      - "3002:3000"

  enrollment:
    build: ./backend/enrollment
    ports:
      - "3003:3000"

  grades:
    build: ./backend/grades
    ports:
      - "3004:3000"
