version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    networks:
      - app-network
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"


networks:
  app-network:
    driver: bridge
