version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dbname

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
